name: pet_match
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_carousel_widget: ^2.0.2
  flutter_countdown_timer: ^4.1.0
  flutter_svg: ^2.0.5
  get_it: ^7.3.0
  google_sign_in: ^6.1.0
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.3+1
  meta: ^1.8.0
  shared_preferences: ^2.1.0
  table_calendar: ^3.0.8
  http: ^0.13.6
  badges: ^3.1.1
  image_picker: ^0.8.7+4
  provider: ^6.0.5
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/welcome_images/
    - assets/images/brand/
    - assets/images/logo.png
    - assets/images/svgs/
    - assets/images/pet_image_placeholder.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
